#!/bin/sh

function run_master {
    vagrant ssh salt -- $@
}

function run_minions {
    for num in 1 2 3
    do
	vagrant ssh minion$num -- $@
    done
}

function run_all {
    run_master $@
    run_minions $@
}

function ssh_master {
    vagrant ssh master
}

vagrant plugin install vagrant-hosts
vagrant up

# Install salt via the PPA
run_all sudo add-apt-repository ppa:saltstack/salt
run_all sudo apt-get update
run_master sudo apt-get -y install salt-master
run_all sudo apt-get -y install salt-minion

# Install salt via the bootstrap script
#run_all curl -L https://bootstrap.saltstack.com -o install_salt.sh
#run_master sudo sh install_salt.sh -P -M
#run_minions sudo sh install_salt.sh -P

# Give some time for the minions to connect with the salt master
sleep 5

run_master sudo salt-key -Ay
