#!/bin/sh

function run_master {
    vagrant ssh salt -- sudo $@
}

function run_minions {
    for num in 1 2 3
    do
	vagrant ssh minion$num -- sudo $@
    done
}

function run_all {
    run_master $@
    run_minions $@
}

function ssh_master {
    vagrant ssh master
}

vagrant plugin install vagrant-hosts
vagrant up

run_all add-apt-repository ppa:saltstack/salt
run_all apt-get update

run_all apt-get -y install salt-minion
run_master apt-get -y install salt-master

# Give some time for the minions to connect with the salt master
sleep 5

run_master salt-key -Ay

run_master salt "*" test.ping
